name: CI
on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version-file: go.mod
      - run: CGO_ENABLED=0 go build -ldflags="-w -s" -v -o app ./cmd/run
      - name: Integration Test
        run: |
          INPUT_TOKEN=${{ secrets.PAT }} INPUT_REPOSITORY=kudoas/sync-issue-field INPUT_ISSUE=3 ./app
